# Generated by Django 4.0.6 on 2022-08-02 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='idCaso',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='caso',
            name='organizacion',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='caso',
            name='tramite',
            field=models.CharField(max_length=254),
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCaso', models.CharField(max_length=254)),
                ('direccion', models.CharField(max_length=254)),
                ('contacto', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('organizacionUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
