# Generated by Django 4.0.6 on 2022-08-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_caso_idcaso_alter_caso_organizacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizacion',
            old_name='idCaso',
            new_name='nombre',
        ),
    ]
