# Generated by Django 4.0.6 on 2022-08-02 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0004_powerup'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='fecha_fin',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('apellido', models.CharField(max_length=254)),
                ('celular', models.CharField(max_length=254)),
                ('estadoSMS', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aprobaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociosEncargados', models.BooleanField(default=False)),
                ('gerenciaFinanciera', models.BooleanField(default=False)),
                ('pagaduria', models.BooleanField(default=False)),
                ('casoEncargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.caso')),
            ],
        ),
    ]
