# Generated by Django 4.0.6 on 2022-08-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_caso_fecha_fin_caso_fecha_inicio_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.organizacion'),
        ),
    ]
