# Generated by Django 4.0.6 on 2022-08-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_caso_organizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='organizacion',
        ),
    ]
