# Generated by Django 4.0.6 on 2022-08-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_caso_organizacionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='fecha_inicio',
            field=models.DateField(blank=True),
        ),
    ]
