# Generated by Django 4.0.6 on 2022-08-03 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0010_remove_contacto_estadosms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aprobaciones',
            options={'verbose_name_plural': 'Aprobaciones'},
        ),
        migrations.RenameField(
            model_name='organizacion',
            old_name='contacto',
            new_name='contacto_organizacion',
        ),
        migrations.RemoveField(
            model_name='aprobaciones',
            name='casoEncargado',
        ),
        migrations.RemoveField(
            model_name='aprobaciones',
            name='gerenciaFinanciera',
        ),
        migrations.RemoveField(
            model_name='aprobaciones',
            name='pagaduria',
        ),
        migrations.RemoveField(
            model_name='aprobaciones',
            name='sociosEncargados',
        ),
        migrations.RemoveField(
            model_name='powerup',
            name='estadoSMS',
        ),
        migrations.RemoveField(
            model_name='powerup',
            name='estadoWhatsapp',
        ),
        migrations.AddField(
            model_name='aprobaciones',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aprobaciones',
            name='contactoQueAprueba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.contacto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='departamento',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='organizacionName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.organizacion'),
        ),
        migrations.AddField(
            model_name='powerup',
            name='name',
            field=models.CharField(default='vacio', max_length=254),
        ),
        migrations.AddField(
            model_name='powerup',
            name='port',
            field=models.CharField(default='8080', max_length=254),
        ),
        migrations.AddField(
            model_name='powerup',
            name='tipo',
            field=models.CharField(default='get', max_length=254),
        ),
        migrations.AddField(
            model_name='powerup',
            name='url',
            field=models.CharField(default='www.url.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='caso',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
