# Generated by Django 4.0.6 on 2022-08-03 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0011_estado_alter_aprobaciones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobaciones',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aprobaciones',
            name='contactoQueAprueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.contacto'),
        ),
    ]
