# Generated by Django 4.0.6 on 2022-08-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_aprobaciones_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='status',
            field=models.CharField(choices=[('1', 'ACTIVO'), ('2', 'INACTIVO'), ('3', 'ABIERTO'), ('4', 'CERRADO')], default='1', max_length=2),
        ),
    ]
