# Generated by Django 4.0.6 on 2022-08-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_estado_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='estado',
        ),
        migrations.AddField(
            model_name='aprobaciones',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.estado'),
        ),
        migrations.AddField(
            model_name='caso',
            name='aprobaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.aprobaciones'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.estado'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='status',
            field=models.CharField(choices=[('1', 'ACTIVO'), ('2', 'INACTIVO'), ('3', 'ABIERTO'), ('4', 'CERRADO')], default='1', max_length=25),
        ),
    ]
