# Generated by Django 4.0.6 on 2022-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_remove_caso_estado_aprobaciones_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO')], default='ACTIVO', max_length=25),
        ),
    ]
