# Generated by Django 4.0.6 on 2022-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_estado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('2', 'INACTIVO'), ('3', 'ABIERTO'), ('4', 'CERRADO')], default='ACTIVO', max_length=25),
        ),
    ]
