# Generated by Django 4.0.6 on 2022-08-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_estado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobaciones',
            name='status',
            field=models.CharField(choices=[('ABI', 'ACTIVO'), ('CERR', 'INACTIVO')], default='ABI', max_length=5),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='status',
            field=models.CharField(choices=[('ACT', 'ACTIVO'), ('INACT', 'INACTIVO')], default='ACT', max_length=5),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='status',
            field=models.CharField(choices=[('ACT', 'ACTIVO'), ('INACT', 'INACTIVO')], default='ACT', max_length=5),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
