# Generated by Django 4.0.6 on 2022-08-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_caso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
