# Generated by Django 4.0.6 on 2022-12-28 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.caso'),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileName',
            field=models.CharField(default='', max_length=254),
        ),
    ]
